### ISSUE TITLE
esc-Boards

### ISSUE THREAD

**Issue by gereic** [ClemensElflein/xESC#3]
Hi,
great project.
I want to build also a lawn-mover and therefore I need this esc.
Can you send me 3 pieces ?

**Comment by ClemensElflein** [comment]
Hi @gereic,
thank you for your message.
I have parts for some motor controllers left, but note that that I had to pay ~45 Eur + Tax for each ESC in parts alone due to semiconductor shortage, so the soldered ones will be quite expensive :slightly_frowning_face: 

Perryc and I are working on a cheap alternative though (based on the RP2040 chip), which will be about 10 Euros + Tax in parts and single sided assembly, so easier to manufacture.

Are you interested in STM32 based ESCs anyways or do you want to wait for the cheaper version to become available? You can also reach out on Discord, I'm more active there.

**Comment by ClemensElflein** [comment]
A community member is providing assembled ESCs now: https://shop.devops.care/openmower/28-xesc-mini-110-stm32-version.html
