### ISSUE TITLE
ESC Boards

### ISSUE THREAD

**Issue by robroy90** [ClemensElflein/xESC#6]
I would like to get 3 of the boards, please. I am willing to pay you for your expenses and time on these, loaded with your custom firmware for the open mower project. I have also donated to your patreon, so thank you for taking up this project and sharing your work and talents with the community! I would also like to get the mainboard for the mower, as I have most of the parts now including the mower itself and the other bits on the way to me.

**Comment by ClemensElflein** [comment]
Hi @robroy90,
thank you for your message and your support on Patreon!

I have parts for some motor controllers left, but note that that I had to pay ~45 Eur + Tax for each ESC in parts alone due to semiconductor shortage, so the soldered ones will be quite expensive :slightly_frowning_face: 

Perryc and I are working on a cheap alternative though (based on the RP2040 chip), which will be about 10 Euros + Tax in parts and single sided assembly, so easier to manufacture.

Are you interested in STM32 based ESCs anyways or do you want to wait for the cheaper version to become available? You can also reach out on Discord, I'm more active there.

**Comment by robroy90** [comment]
I will wait for the cheaper ones, but how will I know when they are available? What about the mainboard? Thanks again!

**Comment by robroy90** [comment]
Just wanted to check in and see how things stood overall? Any closer to getting parts available? THANK YOU!

**Comment by ClemensElflein** [comment]
Parts for the RP2040 version are available, firmware works and the ROS driver is finished. So everything should now work with OpenMower. I'm currently working on creating a video on that, but I need to work on integrating another type of IMU first, because now the MPU9250s are not available anymore and so I can't actually test the driving behavior.

**Comment by robroy90** [comment]
Thanks for the update! Is there a consolidated URL where we can order the remaining parts, such as the mainboard?

**Comment by adouglas89** [comment]
I can prepare an entry using easyEDA on oshwlab.com  similar to https://oshwlab.com/cost.co/20220903_bldc_se3082g . That makes ordering a batch of e.g. ten boards fairly inexpensively with only a few clicks, straight from design files.  I need to go check out and evaluate the RP2040 based one.  I have to have something quiet and I'm a bit worried the RP2040 is not fast enough to provide a quiet system.

**Comment by ClemensElflein** [comment]
A community member is providing assembled ESCs now: https://shop.devops.care/openmower/28-xesc-mini-110-stm32-version.html
